name: CI/CD deploy frontend-celulares-mysql

on: 
  push:
    branches: [ "master" ]  

jobs:
  ci_cd_deploy_frontend_celulares_mysql:
    runs-on: ubuntu-latest

    steps:
      - run: ls -la
      - uses: actions/checkout@v2
      - run: ls -la
      - run: echo 'hello frontend-mysql'

      - name: download, run httpd image
        run: |
          docker run -d --name frontend-mysql httpd

      - name: docker ps
        run: |
          docker ps

      - name: cp frontendMysql content to container
        run: |
          docker cp frontendMysql/. frontend-mysql:/usr/local/apache2/htdocs

      - name: list container contents
        run: |
          docker exec frontend-mysql ls -la /usr/local/apache2/htdocs

      - name: build custom docker image
        run: docker commit --change "ENV MODEL_NAME ${{ secrets.MODEL_NAME }}" frontend-mysql ${{ secrets.DOCKER_USER}}/${{ secrets.MODEL_NAME }}:${{ github.sha }}

      - name: list images
        run: |
          docker images

      - name: docker login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: docker push
        run: docker push ${{ secrets.DOCKER_USER }}/${{ secrets.MODEL_NAME }}:${{ github.sha }}

